version: '3.8'

services:
    redis-master:
        image: redis:latest
        command: redis-server
        ports:
        - "6380:6379"
        networks:
        - redis-cluster

    redis-slave-1:
        image: redis:latest
        command: redis-server --slaveof redis-master 6379
        links:
            - redis-master
        networks:
        - redis-cluster
        
    redis-slave-2:
        image: redis:latest
        command: redis-server --slaveof redis-master 6379
        links:
            - redis-master
        networks:
        - redis-cluster
        
    sentinel-1:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        networks:
        - redis-cluster
        
    sentinel-2:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        networks:
        - redis-cluster
        
    sentinel-3:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        networks:
        - redis-cluster
        
    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        container_name: phpredisadmin
        ports:
            - "8080:80"
        networks:
            - redis-cluster
        environment:
            REDIS_1_HOST: redis-master
            REDIS_1_PORT: 6379
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2

networks:
  redis-cluster:
    driver: bridge